FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
# EXPOSE 7296

# ENV ASPNETCORE_URLS=http://+:7296
ENV ASPNETCORE_ENVIRONMENT=Production

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG configuration=Release
WORKDIR /src

COPY ["./src/ContactsConsumer/Work/Work.csproj",               "src/ContactsConsumer/Work/"]
COPY ["./src/ContactsConsumer/Application/Application.csproj", "src/ContactsConsumer/Application/"]
COPY ["./src/ContactsConsumer/Domain/Domain.csproj"          , "src/ContactsConsumer/Domain/"]
COPY ["./src/ContactsConsumer/Infra/Infra.csproj"            , "src/ContactsConsumer/Infra/"]
COPY ["./src/BuildingBlocks/Contracts/Contracts.csproj"      , "src/BuildingBlocks/"]

RUN dotnet restore "src/ContactsConsumer/Work/Work.csproj"

COPY . .

# WORKDIR "/src/Work"
RUN dotnet build "src/ContactsConsumer/Work/Work.csproj" -c Release -o /app/build

FROM build AS publish
ARG configuration=Release
RUN dotnet publish "src/ContactsConsumer/Work/Work.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Work.dll"]
# ENTRYPOINT ["dotnet", "src/ContactsConsumer/Work/Work.dll"]
