version: '3.4'

volumes:
  db-data:


services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: tech-challenge
      POSTGRES_USER: tech-challenge
      POSTGRES_PASSWORD: tech-challenge
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
