global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'webapi'
    scrape_interval: 5s
    static_configs:
      - targets: ['webapi:7296']
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']