apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: tech-challenge
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s

    scrape_configs:
      - job_name: 'webapi'
        scrape_interval: 5s
        static_configs:
          - targets: ['webapi:7296']

      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus:9090']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: tech-challenge
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
        - containerPort: 9090
        volumeMounts:
        - mountPath: /etc/prometheus/prometheus.yml
          name: prometheus-config
          subPath: prometheus.yml
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: tech-challenge
spec:
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: prometheus
