apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management-alpine
        ports:
        - containerPort: 5672
        - containerPort: 15672
        # volumeMounts:
        # - mountPath: /var/lib/rabbitmq
        #   name: rabbitmq-data
        # - mountPath: /var/log/rabbitmq
        #   name: rabbitmq-logs
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "guest"
        - name: RABBITMQ_DEFAULT_PASS
          value: "guest"
      # volumes:
      # - name: rabbitmq-data
      #   hostPath:
      #     path: ~/.docker-conf/rabbitmq/data
      # - name: rabbitmq-logs
      #   hostPath:
      #     path: ~/.docker-conf/rabbitmq/log
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
  - port: 5672
    targetPort: 5672
    name: aaa
  - port: 15672
    targetPort: 15672
    name: bbb
  selector:
    app: rabbitmq
