apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
  namespace: tech-challenge
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "ConnectionStrings": {
        "DefaultConnection": "Host=db.default.svc.cluster.local; Database=tech-challenge; Username=tech-challenge; Password=tech-challenge"
      },
      "MessageHost": {
        "Host": "amqp://rabbitmq.default.svc.cluster.local:5672",
        "User": "guest",
        "Pass": "guest"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: work
  labels:
    app: work
spec:
  replicas: 1
  selector:
    matchLabels:
      app: work
  template:
    metadata:
      labels:
        app: work
    spec:
      containers:
      - name: work
        image: escorpion559/contactsconsumer:latest
        volumeMounts:
        - mountPath: /app/appsettings.json
          name: worker-config
          subPath: appsettings.json
      volumes:
      - name: worker-config
        configMap:
          name: worker-config