name: .NET

on:
  push:
    branches: [ "main", "develop", "refac-microservices" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services: 
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: tech-challenge
          POSTGRES_PASSWORD: tech-challenge
          POSTGRES_DB: tech-challenge
        ports:
          - 5432:5432
        options: > 
          --health-cmd="pg_isready -U tech-challenge"
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Docker Login
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASS }}
    
    - name: Build and push Docker image for Contacts
      uses: docker/build-push-action@v5.4.0
      with:
        context: .
        file: ./dockerfile-contacts
        tags: 'escorpion559/contacts:latest'
        push: true
    
    - name: Build and push Docker image for ContactsConsumer
      uses: docker/build-push-action@v5.4.0
      with:
        context: .
        file: ./dockerfile-contacts-consumer
        tags: 'escorpion559/contactsconsumer:latest'
        push: true
